import { Square, Star, Tag } from 'lucide-react';
import type { ComponentDefinition } from '@/types/component';
import {
  BADGE_ICON_POSITION_OPTIONS,
  BUTTON_ICON_VARIANT_OPTIONS,
  BUTTON_TYPE_OPTIONS,
  BUTTON_VARIANT_OPTIONS,
  ICON_POSITION_OPTIONS,
  ICON_SIZE_OPTIONS,
} from '../shared/options';
import { LEAF_COMPOSITION, LEAF_SPACING, lwcOutput } from '../shared/composition';

export const BASIC_COMPONENTS: ComponentDefinition[] = [
  {
    type: 'lightning-button',
    salesforceName: 'lightning-button',
    displayName: 'Button',
    category: 'Basic',
    description: 'A clickable element used to perform an action.',
    icon: Square,
    composition: LEAF_COMPOSITION,
    styleCapabilities: LEAF_SPACING,
    defaultAttributes: {
      label: 'Button',
      variant: 'neutral',
      type: 'button',
    },
    properties: [
      {
        name: 'label',
        attributeName: 'label',
        label: 'Label',
        type: 'text',
        defaultValue: 'Button',
        description: 'The text to be displayed inside the button.',
        placeholder: 'Button label',
      },
      {
        name: 'variant',
        attributeName: 'variant',
        label: 'Variant',
        type: 'select',
        defaultValue: 'neutral',
        description:
          'Accepted variants: base, neutral, brand, brand-outline, destructive, destructive-text, inverse, and success. Defaults to neutral.',
        options: BUTTON_VARIANT_OPTIONS,
      },
      {
        name: 'type',
        attributeName: 'type',
        label: 'Type',
        type: 'select',
        defaultValue: 'button',
        description: 'Valid values are button, reset, and submit. Defaults to button.',
        options: BUTTON_TYPE_OPTIONS,
      },
      {
        name: 'icon-name',
        attributeName: 'icon-name',
        label: 'Icon Name',
        type: 'text',
        description:
          "Lightning Design System utility icon in the format 'utility:down'. Only the utility category is supported on lightning-button.",
        placeholder: 'e.g. utility:down',
      },
      {
        name: 'icon-position',
        attributeName: 'icon-position',
        label: 'Icon Position',
        type: 'select',
        defaultValue: 'left',
        description: 'Position of the icon relative to the label. Defaults to left.',
        options: ICON_POSITION_OPTIONS,
      },
      {
        name: 'disabled',
        attributeName: 'disabled',
        label: 'Disabled',
        type: 'boolean',
        defaultValue: false,
        description: 'If present, the button is disabled and users cannot interact with it.',
      },
      {
        name: 'stretch',
        attributeName: 'stretch',
        label: 'Stretch',
        type: 'boolean',
        defaultValue: false,
        description: 'If true, the button takes up the entire available width. Defaults to false.',
      },
      {
        name: 'name',
        attributeName: 'name',
        label: 'Name',
        type: 'text',
        description: 'Optional name used to identify the button in a callback.',
        placeholder: 'Button name',
      },
      {
        name: 'value',
        attributeName: 'value',
        label: 'Value',
        type: 'text',
        description: 'Optional value used when submitting a form.',
        placeholder: 'Button value',
      },
      {
        name: 'title',
        attributeName: 'title',
        label: 'Title',
        type: 'text',
        description: 'Tooltip text displayed when the mouse moves over the button.',
        placeholder: 'Tooltip text',
      },
    ],
    canvas: { kind: 'leaf', previewKind: 'button', previewLabelProperty: 'label' },
    output: lwcOutput('lightning-button'),
  },

  {
    type: 'lightning-button-icon',
    salesforceName: 'lightning-button-icon',
    displayName: 'Button Icon',
    category: 'Basic',
    description: 'An icon-only button.',
    icon: Star,
    composition: LEAF_COMPOSITION,
    styleCapabilities: LEAF_SPACING,
    defaultAttributes: {
      'icon-name': 'utility:question',
      'alternative-text': 'Icon button',
      variant: 'border',
      size: 'medium',
    },
    properties: [
      {
        name: 'icon-name',
        attributeName: 'icon-name',
        label: 'Icon Name',
        type: 'text',
        defaultValue: 'utility:question',
        required: true,
        description:
          "Lightning Design System name of the icon in the format 'utility:down'.",
        placeholder: 'e.g. utility:close',
      },
      {
        name: 'alternative-text',
        attributeName: 'alternative-text',
        label: 'Alternative Text',
        type: 'text',
        defaultValue: 'Icon button',
        required: true,
        description:
          "Accessible name describing the button action, for example 'Close window', not the icon appearance.",
        placeholder: 'Accessible label',
      },
      {
        name: 'variant',
        attributeName: 'variant',
        label: 'Variant',
        type: 'select',
        defaultValue: 'border',
        description:
          'Accepted variants: bare, bare-inverse, border, border-filled, border-inverse, brand, and container. Defaults to border.',
        options: BUTTON_ICON_VARIANT_OPTIONS,
      },
      {
        name: 'size',
        attributeName: 'size',
        label: 'Size',
        type: 'select',
        defaultValue: 'medium',
        description:
          'For bare and bare-inverse, size applies to the icon. For other variants, size applies to the button. Defaults to medium.',
        options: ICON_SIZE_OPTIONS,
      },
      {
        name: 'disabled',
        attributeName: 'disabled',
        label: 'Disabled',
        type: 'boolean',
        defaultValue: false,
        description: 'If present, users cannot interact with the button.',
      },
      {
        name: 'type',
        attributeName: 'type',
        label: 'Type',
        type: 'select',
        defaultValue: 'button',
        description: 'Valid values are button, reset, and submit. Defaults to button.',
        options: BUTTON_TYPE_OPTIONS,
      },
      {
        name: 'name',
        attributeName: 'name',
        label: 'Name',
        type: 'text',
        description: 'Optional name used to identify the button in a callback.',
        placeholder: 'Button name',
      },
      {
        name: 'value',
        attributeName: 'value',
        label: 'Value',
        type: 'text',
        description: 'Optional value used when submitting a form.',
        placeholder: 'Button value',
      },
      {
        name: 'title',
        attributeName: 'title',
        label: 'Title',
        type: 'text',
        description: 'Native browser tooltip. Overrides hover text from alternative-text.',
        placeholder: 'Tooltip text',
      },
      {
        name: 'tooltip',
        attributeName: 'tooltip',
        label: 'Tooltip',
        type: 'text',
        description:
          'Contextual popup shown on hover or keyboard focus. Linked with aria-describedby.',
        placeholder: 'Popup text',
      },
      {
        name: 'icon-class',
        attributeName: 'icon-class',
        label: 'Icon Class',
        type: 'text',
        description: 'CSS class applied to the icon element.',
        placeholder: 'e.g. slds-icon-text-error',
      },
    ],
    canvas: { kind: 'leaf', previewKind: 'button-icon', previewLabelProperty: 'alternative-text' },
    output: lwcOutput('lightning-button-icon'),
  },

  {
    type: 'lightning-badge',
    salesforceName: 'lightning-badge',
    displayName: 'Badge',
    category: 'Basic',
    description:
      'A label that holds a small amount of information, such as the number of unread notifications. Nested elements are not supported.',
    icon: Tag,
    composition: LEAF_COMPOSITION,
    styleCapabilities: LEAF_SPACING,
    defaultAttributes: {
      label: 'Badge',
    },
    properties: [
      {
        name: 'label',
        attributeName: 'label',
        label: 'Label',
        type: 'text',
        defaultValue: 'Badge',
        required: true,
        description: 'The text to be displayed inside the badge.',
        placeholder: 'Badge text',
      },
      {
        name: 'icon-name',
        attributeName: 'icon-name',
        label: 'Icon Name',
        type: 'text',
        description:
          "Lightning Design System icon in the format 'utility:down'. Displayed before the text by default.",
        placeholder: 'e.g. standard:account',
      },
      {
        name: 'icon-position',
        attributeName: 'icon-position',
        label: 'Icon Position',
        type: 'select',
        defaultValue: 'start',
        description: "Possible values: 'start' (before the text) and 'end' (after the text).",
        options: BADGE_ICON_POSITION_OPTIONS,
      },
      {
        name: 'icon-alternative-text',
        attributeName: 'icon-alternative-text',
        label: 'Icon Alternative Text',
        type: 'text',
        description: 'Alternative text for the icon, displayed as tooltip text.',
        placeholder: 'Icon description',
      },
    ],
    canvas: { kind: 'leaf', previewKind: 'badge', previewLabelProperty: 'label' },
    output: lwcOutput('lightning-badge'),
  },
];
