import { Table } from 'lucide-react';
import type { ComponentDefinition, ComponentPropertyDefinition } from '@/types/component';
import { LEAF_COMPOSITION, LEAF_SPACING, lwcOutput } from '../shared/composition';
import { whenEquals, whenIn, whenNotEquals, whenNotIn } from '../shared/conditions';
import { BUTTON_ICON_VARIANT_OPTIONS, BUTTON_VARIANT_OPTIONS, CURRENCY_DISPLAY_OPTIONS, ICON_POSITION_OPTIONS } from '../shared/options';
import {
  DATATABLE_ALIGNMENT_OPTIONS,
  DATATABLE_COLUMN_TYPE_OPTIONS,
  DATATABLE_DATE_PART_OPTIONS,
  DATATABLE_MENU_ALIGNMENT_OPTIONS,
  DATATABLE_MONTH_OPTIONS,
  DATATABLE_NON_ALIGNMENT_TYPES,
  DATATABLE_NON_EDITABLE_TYPES,
  DATATABLE_NON_READ_ONLY_ICON_TYPES,
  DATATABLE_NON_SORTABLE_TYPES,
  DATATABLE_NON_WRAP_TYPES,
  DATATABLE_URL_TARGET_OPTIONS,
  defaultDatatableColumns,
  defaultDatatableRowActions,
  toSalesforceColumns,
} from '../datatable/columns';

const COLUMN_WIDTHS_MODE_OPTIONS = [
  { label: 'Fixed', value: 'fixed' },
  { label: 'Auto', value: 'auto' },
];

const SORT_DIRECTION_OPTIONS = [
  { label: 'Ascending', value: 'asc' },
  { label: 'Descending', value: 'desc' },
];

const WRAP_TABLE_HEADER_OPTIONS = [
  { label: 'None', value: 'none' },
  { label: 'All', value: 'all' },
  { label: 'By Column', value: 'by-column' },
];

const SINGLE_ROW_SELECTION_OPTIONS = [
  { label: 'Radio', value: 'radio' },
  { label: 'Checkbox', value: 'checkbox' },
];

function nestedTypeAttribute(
  name: string,
  config: Omit<ComponentPropertyDefinition, 'name' | 'nestedObject'>
): ComponentPropertyDefinition {
  return { name, nestedObject: 'typeAttributes', ...config };
}

const DATATABLE_ROW_ACTION_PROPERTIES: ComponentPropertyDefinition[] = [
  {
    name: 'label',
    label: 'Label',
    type: 'text',
    required: true,
    description: 'Required. Label shown in the row action menu.',
    placeholder: 'Show details',
  },
  {
    name: 'name',
    label: 'Name',
    type: 'text',
    required: true,
    description: 'Required. Identifies the selected action in onrowaction.',
    placeholder: 'show_details',
  },
  {
    name: 'disabled',
    label: 'Disabled',
    type: 'boolean',
    defaultValue: false,
    description: 'If true, the action item is shown as disabled. Defaults to false.',
  },
  {
    name: 'iconName',
    label: 'Icon Name',
    type: 'text',
    description: 'SLDS icon shown to the right of the action item.',
    placeholder: 'utility:delete',
  },
];

const DATATABLE_HEADER_ACTION_PROPERTIES: ComponentPropertyDefinition[] = [
  {
    name: 'label',
    label: 'Label',
    type: 'text',
    required: true,
    description: 'Required. Label shown in the column header action menu.',
    placeholder: 'All',
  },
  {
    name: 'name',
    label: 'Name',
    type: 'text',
    required: true,
    description: 'Required. Identifies the selected header action in onheaderaction.',
    placeholder: 'all',
  },
  {
    name: 'checked',
    label: 'Checked',
    type: 'boolean',
    defaultValue: false,
    description: 'If true, a check mark is shown to the left of the action label.',
  },
  {
    name: 'disabled',
    label: 'Disabled',
    type: 'boolean',
    defaultValue: false,
    description: 'If true, the action item is shown as disabled. Defaults to false.',
  },
  {
    name: 'iconName',
    label: 'Icon Name',
    type: 'text',
    description: 'SLDS icon shown to the right of the action item.',
    placeholder: 'utility:filterList',
  },
];

const DATATABLE_COLUMN_ITEM_PROPERTIES: ComponentPropertyDefinition[] = [
  {
    name: 'label',
    label: 'Label',
    type: 'text',
    required: true,
    description: 'Text label in the column header.',
    placeholder: 'Column label',
  },
  {
    name: 'fieldName',
    label: 'Field Name',
    type: 'text',
    required: true,
    description: 'Binds the column to a property on each data row. Case-sensitive.',
    placeholder: 'e.g. Name',
  },
  {
    name: 'type',
    label: 'Type',
    type: 'select',
    defaultValue: 'text',
    description: 'Salesforce datatable data type used to format the cell.',
    options: DATATABLE_COLUMN_TYPE_OPTIONS,
  },
  {
    name: 'sortable',
    label: 'Sortable',
    type: 'boolean',
    defaultValue: false,
    description: 'If true, the column header can be used to sort rows. Handle onsort in JavaScript.',
    visibleWhen: whenNotIn('type', DATATABLE_NON_SORTABLE_TYPES),
  },
  {
    name: 'editable',
    label: 'Editable',
    type: 'boolean',
    defaultValue: false,
    description:
      'If true, the column supports inline editing. Not supported for date or location fields.',
    visibleWhen: whenNotIn('type', DATATABLE_NON_EDITABLE_TYPES),
  },
  {
    name: 'displayReadOnlyIcon',
    label: 'Display Read Only Icon',
    type: 'boolean',
    defaultValue: false,
    description:
      'Shows a lock icon on cells in this column. Set editable to false (or leave it off) when using this.',
    visibleWhen: [
      whenNotIn('type', DATATABLE_NON_READ_ONLY_ICON_TYPES),
      whenNotEquals('editable', true),
    ],
  },
  {
    name: 'wrapText',
    label: 'Wrap Text',
    type: 'boolean',
    defaultValue: false,
    description: 'If true, cell text wraps when the table renders.',
    visibleWhen: whenNotIn('type', DATATABLE_NON_WRAP_TYPES),
  },
  {
    name: 'alignment',
    nestedObject: 'cellAttributes',
    label: 'Alignment',
    type: 'select',
    description:
      'Horizontal alignment for cell content (cellAttributes.alignment). Not used for action columns, which are centered.',
    options: DATATABLE_ALIGNMENT_OPTIONS,
    visibleWhen: whenNotIn('type', DATATABLE_NON_ALIGNMENT_TYPES),
  },
  {
    name: 'initialWidth',
    label: 'Initial Width',
    type: 'number',
    min: 50,
    max: 1000,
    description: 'Column width in pixels when initialized. Ignored if Fixed Width is set.',
    placeholder: 'px',
  },
  {
    name: 'fixedWidth',
    label: 'Fixed Width',
    type: 'number',
    min: 50,
    max: 1000,
    description: 'Fixed column width in pixels. Makes the column non-resizable.',
    placeholder: 'px',
  },
  {
    name: 'hideDefaultActions',
    label: 'Hide Default Actions',
    type: 'boolean',
    defaultValue: false,
    description: 'Hides the default wrap/clip header actions on this column.',
  },
  {
    name: 'hideLabel',
    label: 'Hide Label',
    type: 'boolean',
    defaultValue: false,
    description: 'Hides the column header label. Use with Header Icon Name or Image Source.',
  },
  {
    name: 'iconName',
    label: 'Header Icon Name',
    type: 'text',
    description:
      'SLDS icon appended to the left of the header label (column iconName). Use utility or standard icons.',
    placeholder: 'utility:trending',
  },
  {
    name: 'imgSrc',
    label: 'Header Image Source',
    type: 'text',
    description:
      'URI for a custom header image. iconName is used as a fallback if the image fails to load.',
    placeholder: 'https://…',
  },
  {
    name: 'actions',
    label: 'Header Actions',
    type: 'object-list',
    description:
      'Custom column header actions (columns[].actions). Stored for future JS generation; not emitted in HTML.',
    itemSchema: {
      defaultItem: { label: 'All', name: 'all' },
      titleProperty: 'label',
      addLabel: 'Add header action',
      emptyLabel: 'No custom header actions. Default wrap/clip actions still apply unless hidden.',
      properties: DATATABLE_HEADER_ACTION_PROPERTIES,
    },
  },
  nestedTypeAttribute('rowActions', {
    label: 'Row Actions',
    type: 'object-list',
    required: true,
    description:
      'Required typeAttributes.rowActions for action columns. Stored for future JS generation; not emitted in HTML.',
    defaultValue: defaultDatatableRowActions(),
    visibleWhen: whenEquals('type', 'action'),
    itemSchema: {
      defaultItem: { label: 'New Action', name: 'new_action' },
      titleProperty: 'label',
      addLabel: 'Add row action',
      emptyLabel: 'An action column requires at least one row action.',
      minItems: 1,
      properties: DATATABLE_ROW_ACTION_PROPERTIES,
    },
  }),
  nestedTypeAttribute('linkify', {
    label: 'Linkify',
    type: 'boolean',
    defaultValue: false,
    description: 'For text columns, display URLs and email addresses as links.',
    visibleWhen: whenEquals('type', 'text'),
  }),
  nestedTypeAttribute('currencyCode', {
    label: 'Currency Code',
    type: 'text',
    description: 'ISO 4217 currency code used when type is currency (typeAttributes.currencyCode).',
    placeholder: 'e.g. USD',
    visibleWhen: whenEquals('type', 'currency'),
  }),
  nestedTypeAttribute('currencyDisplayAs', {
    label: 'Currency Display As',
    type: 'select',
    defaultValue: 'symbol',
    description: 'How currency is displayed: symbol, code, or name.',
    options: CURRENCY_DISPLAY_OPTIONS,
    visibleWhen: whenEquals('type', 'currency'),
  }),
  nestedTypeAttribute('step', {
    label: 'Step',
    type: 'text',
    description: 'Granularity for inline editing of currency or percent values.',
    placeholder: 'e.g. 0.01',
    visibleWhen: whenIn('type', ['currency', 'percent']),
  }),
  nestedTypeAttribute('minimumFractionDigits', {
    label: 'Min Fraction Digits',
    type: 'number',
    min: 0,
    max: 20,
    description: 'Minimum fraction digits for number, currency, or percent columns.',
    visibleWhen: whenIn('type', ['number', 'currency', 'percent']),
  }),
  nestedTypeAttribute('maximumFractionDigits', {
    label: 'Max Fraction Digits',
    type: 'number',
    min: 0,
    max: 20,
    description: 'Maximum fraction digits for number, currency, or percent columns.',
    visibleWhen: whenIn('type', ['number', 'currency', 'percent']),
  }),
  nestedTypeAttribute('label', {
    label: 'Link Label',
    type: 'text',
    description: 'Visible text for a url column (typeAttributes.label).',
    placeholder: 'Display label',
    visibleWhen: whenEquals('type', 'url'),
  }),
  nestedTypeAttribute('target', {
    label: 'Target',
    type: 'select',
    description: 'Browsing context for a url column.',
    options: DATATABLE_URL_TARGET_OPTIONS,
    visibleWhen: whenEquals('type', 'url'),
  }),
  nestedTypeAttribute('tooltip', {
    label: 'Tooltip',
    type: 'text',
    description: 'Tooltip shown on a url column.',
    visibleWhen: whenEquals('type', 'url'),
  }),
  nestedTypeAttribute('year', {
    label: 'Year',
    type: 'select',
    description: 'Date year display format.',
    options: DATATABLE_DATE_PART_OPTIONS,
    visibleWhen: whenIn('type', ['date', 'date-local']),
  }),
  nestedTypeAttribute('month', {
    label: 'Month',
    type: 'select',
    description: 'Date month display format.',
    options: DATATABLE_MONTH_OPTIONS,
    visibleWhen: whenIn('type', ['date', 'date-local']),
  }),
  nestedTypeAttribute('day', {
    label: 'Day',
    type: 'select',
    description: 'Date day display format.',
    options: DATATABLE_DATE_PART_OPTIONS,
    visibleWhen: whenIn('type', ['date', 'date-local']),
  }),
  nestedTypeAttribute('latitude', {
    label: 'Latitude Field',
    type: 'text',
    description: 'Field name on the row that holds latitude (typeAttributes.latitude).',
    placeholder: 'e.g. lat',
    visibleWhen: whenEquals('type', 'location'),
  }),
  nestedTypeAttribute('longitude', {
    label: 'Longitude Field',
    type: 'text',
    description: 'Field name on the row that holds longitude (typeAttributes.longitude).',
    placeholder: 'e.g. lon',
    visibleWhen: whenEquals('type', 'location'),
  }),
  nestedTypeAttribute('label', {
    label: 'Button Label',
    type: 'text',
    description: 'Label for a button column.',
    placeholder: 'Button',
    visibleWhen: whenEquals('type', 'button'),
  }),
  nestedTypeAttribute('name', {
    label: 'Action Name',
    type: 'text',
    description: 'Name passed to row action handlers for button or button-icon columns.',
    placeholder: 'e.g. edit',
    visibleWhen: whenIn('type', ['button', 'button-icon']),
  }),
  nestedTypeAttribute('variant', {
    label: 'Button Variant',
    type: 'select',
    description: 'lightning-button variant for a button column.',
    options: BUTTON_VARIANT_OPTIONS,
    visibleWhen: whenEquals('type', 'button'),
  }),
  nestedTypeAttribute('iconName', {
    label: 'Icon Name',
    type: 'text',
    description: 'Lightning Design System icon name, for example utility:edit.',
    placeholder: 'utility:edit',
    visibleWhen: whenIn('type', ['button', 'button-icon']),
  }),
  nestedTypeAttribute('title', {
    label: 'Title',
    type: 'text',
    description: 'Tooltip title for a button or button-icon column.',
    visibleWhen: whenIn('type', ['button', 'button-icon']),
  }),
  nestedTypeAttribute('iconPosition', {
    label: 'Icon Position',
    type: 'select',
    description: 'Icon position on a button column.',
    options: ICON_POSITION_OPTIONS,
    visibleWhen: whenEquals('type', 'button'),
  }),
  nestedTypeAttribute('disabled', {
    label: 'Disabled',
    type: 'boolean',
    defaultValue: false,
    description: 'Disables a button or button-icon column.',
    visibleWhen: whenIn('type', ['button', 'button-icon']),
  }),
  nestedTypeAttribute('alternativeText', {
    label: 'Alternative Text',
    type: 'text',
    description: 'Assistive text for a button-icon column.',
    visibleWhen: whenEquals('type', 'button-icon'),
  }),
  nestedTypeAttribute('variant', {
    label: 'Icon Variant',
    type: 'select',
    description: 'lightning-button-icon variant.',
    options: BUTTON_ICON_VARIANT_OPTIONS,
    visibleWhen: whenEquals('type', 'button-icon'),
  }),
  nestedTypeAttribute('menuAlignment', {
    label: 'Menu Alignment',
    type: 'select',
    defaultValue: 'right',
    description: 'Dropdown alignment for an action column. Default is right.',
    options: DATATABLE_MENU_ALIGNMENT_OPTIONS,
    visibleWhen: whenEquals('type', 'action'),
  }),
];

const DEFAULT_DATATABLE_COLUMNS = defaultDatatableColumns();

export const DATATABLE_COMPONENTS: ComponentDefinition[] = [
  {
    type: 'lightning-datatable',
    salesforceName: 'lightning-datatable',
    displayName: 'Datatable',
    category: 'Display',
    description:
      'A table that displays rows and columns of data. Column formatting, selection, and sorting are configured here; row data is supplied from JavaScript at runtime. Not supported on Salesforce mobile runtime.',
    icon: Table,
    composition: LEAF_COMPOSITION,
    styleCapabilities: LEAF_SPACING,
    defaultAttributes: {
      'key-field': 'Id',
      data: 'data',
      columns: DEFAULT_DATATABLE_COLUMNS,
      'hide-checkbox-column': false,
      'show-row-number-column': false,
      'resize-column-disabled': false,
      'column-widths-mode': 'fixed',
      'hide-table-header': false,
      'is-loading': false,
      'enable-infinite-loading': false,
      'default-sort-direction': 'asc',
      'wrap-table-header': 'none',
    },
    properties: [
      {
        name: 'key-field',
        attributeName: 'key-field',
        label: 'Key Field',
        type: 'text',
        defaultValue: 'Id',
        required: true,
        description:
          'Required. Unique row identifier field. Case-sensitive and must match a property on each data row.',
        placeholder: 'Id',
      },
      {
        name: 'data',
        attributeName: 'data',
        label: 'Data',
        type: 'text',
        htmlAttribute: false,
        outputKind: 'binding',
        jsBinding: 'data',
        jsRole: 'internal-field',
        jsInitializer: 'empty-array',
        defaultValue: 'data',
        required: true,
        description:
          'JavaScript array of row objects. Emitted as data={data}. The canvas shows design-time sample rows generated from columns, not Salesforce records.',
        placeholder: 'data',
      },
      {
        name: 'columns',
        attributeName: 'columns',
        label: 'Columns',
        type: 'object-list',
        htmlAttribute: false,
        outputKind: 'binding',
        jsBinding: 'columns',
        jsRole: 'internal-field',
        jsInitializer: 'literal',
        serializeJsValue: toSalesforceColumns,
        required: true,
        description:
          'JavaScript column definitions. Emitted as columns={columns}. Edit the array below; do not paste raw JSON.',
        defaultValue: DEFAULT_DATATABLE_COLUMNS,
        itemSchema: {
          defaultItem: { label: 'New Column', fieldName: 'Field', type: 'text' },
          titleProperty: 'label',
          addLabel: 'Add column',
          emptyLabel: 'No columns yet. Add a column to define the table.',
          properties: DATATABLE_COLUMN_ITEM_PROPERTIES,
        },
      },
      {
        name: 'hide-checkbox-column',
        attributeName: 'hide-checkbox-column',
        label: 'Hide Checkbox Column',
        type: 'boolean',
        defaultValue: false,
        description: 'If present, the checkbox or radio column for row selection is hidden.',
      },
      {
        name: 'show-row-number-column',
        attributeName: 'show-row-number-column',
        label: 'Show Row Number Column',
        type: 'boolean',
        defaultValue: false,
        description: 'If present, row numbers are shown in the first column.',
      },
      {
        name: 'row-number-offset',
        attributeName: 'row-number-offset',
        label: 'Row Number Offset',
        type: 'number',
        defaultValue: 0,
        description: 'Where to start counting the row number. The default is 0.',
        visibleWhen: whenEquals('show-row-number-column', true),
      },
      {
        name: 'max-row-selection',
        attributeName: 'max-row-selection',
        label: 'Max Row Selection',
        type: 'number',
        min: 1,
        description:
          'Maximum number of rows that can be selected. Use 1 for single selection (radio buttons by default).',
        placeholder: 'e.g. 1',
      },
      {
        name: 'single-row-selection-mode',
        attributeName: 'single-row-selection-mode',
        label: 'Single Row Selection Mode',
        type: 'select',
        defaultValue: 'radio',
        description:
          'When max-row-selection is 1, radio buttons are used by default. Set checkbox to keep checkboxes.',
        options: SINGLE_ROW_SELECTION_OPTIONS,
        visibleWhen: whenEquals('max-row-selection', 1),
      },
      {
        name: 'selected-rows',
        attributeName: 'selected-rows',
        label: 'Selected Rows',
        type: 'text',
        htmlAttribute: false,
        outputKind: 'binding',
        jsRole: 'internal-field',
        jsInitializer: 'empty-array',
        jsBinding: 'selectedRows',
        description:
          'JavaScript list of key-field values for programmatically selected rows. Enter a JS identifier to emit selected-rows={name}. Leave blank to omit.',
        placeholder: 'selectedRows',
      },
      {
        name: 'disabled-rows',
        attributeName: 'disabled-rows',
        label: 'Disabled Rows',
        type: 'text',
        htmlAttribute: false,
        outputKind: 'binding',
        jsRole: 'internal-field',
        jsInitializer: 'empty-array',
        jsBinding: 'disabledRows',
        description:
          'JavaScript list of key-field values for programmatically disabled rows. Enter a JS identifier to emit disabled-rows={name}. Leave blank to omit.',
        placeholder: 'disabledRows',
      },
      {
        name: 'resize-column-disabled',
        attributeName: 'resize-column-disabled',
        label: 'Resize Column Disabled',
        type: 'boolean',
        defaultValue: false,
        description: 'If present, users cannot resize columns.',
      },
      {
        name: 'resize-step',
        attributeName: 'resize-step',
        label: 'Resize Step',
        type: 'number',
        min: 1,
        description:
          'Pixels to resize a column when the user presses the left or right arrow. Salesforce default is 10.',
        placeholder: '10',
      },
      {
        name: 'column-widths-mode',
        attributeName: 'column-widths-mode',
        label: 'Column Widths Mode',
        type: 'select',
        defaultValue: 'fixed',
        description: 'fixed gives equal column widths. auto sizes columns from content. Default is fixed.',
        options: COLUMN_WIDTHS_MODE_OPTIONS,
      },
      {
        name: 'max-column-width',
        attributeName: 'max-column-width',
        label: 'Max Column Width',
        type: 'number',
        min: 1,
        description: 'Maximum width for all columns in pixels. Salesforce default is 1000.',
        placeholder: '1000',
      },
      {
        name: 'min-column-width',
        attributeName: 'min-column-width',
        label: 'Min Column Width',
        type: 'number',
        min: 1,
        description: 'Minimum width for all columns in pixels. Salesforce default is 50.',
        placeholder: '50',
      },
      {
        name: 'wrap-text-max-lines',
        attributeName: 'wrap-text-max-lines',
        label: 'Wrap Text Max Lines',
        type: 'number',
        min: 1,
        description: 'Number of lines after which wrapped cell content is cut off. Must be at least 1.',
        placeholder: 'e.g. 3',
      },
      {
        name: 'wrap-table-header',
        attributeName: 'wrap-table-header',
        label: 'Wrap Table Header',
        type: 'select',
        defaultValue: 'none',
        description: 'How column headers wrap: none, all, or by-column. Default is none.',
        options: WRAP_TABLE_HEADER_OPTIONS,
      },
      {
        name: 'hide-table-header',
        attributeName: 'hide-table-header',
        label: 'Hide Table Header',
        type: 'boolean',
        defaultValue: false,
        description: 'If present, the table header is hidden.',
      },
      {
        name: 'hide-borders',
        attributeName: 'hide-borders',
        label: 'Hide Borders',
        type: 'boolean',
        defaultValue: false,
        description: 'If present, table borders are hidden. Only valid when hide-table-header is true.',
        visibleWhen: whenEquals('hide-table-header', true),
      },
      {
        name: 'is-loading',
        attributeName: 'is-loading',
        label: 'Is Loading',
        type: 'boolean',
        defaultValue: false,
        description: 'If present, a spinner is shown to indicate that more data is loading.',
      },
      {
        name: 'enable-infinite-loading',
        attributeName: 'enable-infinite-loading',
        label: 'Enable Infinite Loading',
        type: 'boolean',
        defaultValue: false,
        description:
          'If present, more data can be loaded when scrolling to the end of the table. Use with onloadmore.',
      },
      {
        name: 'load-more-offset',
        attributeName: 'load-more-offset',
        label: 'Load More Offset',
        type: 'number',
        defaultValue: 20,
        description: 'Pixels from the bottom of the table that trigger infinite loading. Default is 20.',
        visibleWhen: whenEquals('enable-infinite-loading', true),
      },
      {
        name: 'sorted-by',
        attributeName: 'sorted-by',
        label: 'Sorted By',
        type: 'text',
        description: 'Column fieldName or column key that currently controls sort order. Update this from onsort.',
        placeholder: 'e.g. Name',
      },
      {
        name: 'sorted-direction',
        attributeName: 'sorted-direction',
        label: 'Sorted Direction',
        type: 'select',
        description: 'Current sort direction. Valid options are asc and desc.',
        options: SORT_DIRECTION_OPTIONS,
      },
      {
        name: 'default-sort-direction',
        attributeName: 'default-sort-direction',
        label: 'Default Sort Direction',
        type: 'select',
        defaultValue: 'asc',
        description: 'Sorting direction on an unsorted column. Default is asc.',
        options: SORT_DIRECTION_OPTIONS,
      },
      {
        name: 'show-actions-menu',
        attributeName: 'show-actions-menu',
        label: 'Show Actions Menu',
        type: 'boolean',
        defaultValue: false,
        description: 'If present, the actions menu is displayed so users can do advanced sorting.',
      },
      {
        name: 'suppress-bottom-bar',
        attributeName: 'suppress-bottom-bar',
        label: 'Suppress Bottom Bar',
        type: 'boolean',
        defaultValue: false,
        description: 'If present, the Save and Cancel footer is hidden during inline editing.',
      },
      {
        name: 'draft-values',
        attributeName: 'draft-values',
        label: 'Draft Values',
        type: 'text',
        htmlAttribute: false,
        outputKind: 'binding',
        jsRole: 'internal-field',
        jsInitializer: 'empty-object',
        jsBinding: 'draftValues',
        description:
          'JavaScript object of per-row inline-edit values. Enter a JS identifier to emit draft-values={name}. Leave blank to omit.',
        placeholder: 'draftValues',
      },
      {
        name: 'errors',
        attributeName: 'errors',
        label: 'Errors',
        type: 'text',
        htmlAttribute: false,
        outputKind: 'binding',
        jsRole: 'internal-field',
        jsInitializer: 'empty-object',
        jsBinding: 'errors',
        description:
          'JavaScript object of cell, row, and table errors. Enter a JS identifier to emit errors={name}. Leave blank to omit.',
        placeholder: 'errors',
      },
      {
        name: 'aria-label',
        attributeName: 'aria-label',
        label: 'ARIA Label',
        type: 'text',
        description: 'Accessible name that identifies this table from others on the page.',
        placeholder: 'Table label',
      },
      {
        name: 'aria-labelled-by',
        attributeName: 'aria-labelled-by',
        label: 'ARIA Labelled By',
        type: 'text',
        description:
          'Public lightning-datatable attribute that passes aria-labelledby to the inner table. Space-separated element IDs of visible descriptive text.',
        placeholder: 'table-desc',
      },
      {
        name: 'aria-describedby',
        attributeName: 'aria-describedby',
        label: 'ARIA Described By',
        type: 'text',
        description:
          'ID or space-separated IDs of elements that describe this table. Documented in Salesforce datatable accessibility guidance.',
        placeholder: 'table-help',
      },
      {
        name: 'onrowselection',
        attributeName: 'onrowselection',
        label: 'onrowselection',
        type: 'text',
        outputKind: 'event',
        jsRole: 'handler',
        description: 'Handler for row selection. Emitted only when a JavaScript identifier is set.',
        placeholder: 'handleRowSelection',
      },
      {
        name: 'onrowaction',
        attributeName: 'onrowaction',
        label: 'onrowaction',
        type: 'text',
        outputKind: 'event',
        jsRole: 'handler',
        description: 'Handler for row-level actions. Emitted only when a JavaScript identifier is set.',
        placeholder: 'handleRowAction',
      },
      {
        name: 'onheaderaction',
        attributeName: 'onheaderaction',
        label: 'onheaderaction',
        type: 'text',
        outputKind: 'event',
        jsRole: 'handler',
        description: 'Handler for column header actions. Emitted only when a JavaScript identifier is set.',
        placeholder: 'handleHeaderAction',
      },
      {
        name: 'onsort',
        attributeName: 'onsort',
        label: 'onsort',
        type: 'text',
        outputKind: 'event',
        jsRole: 'handler',
        description: 'Handler for column sorting. Emitted only when a JavaScript identifier is set.',
        placeholder: 'handleSort',
      },
      {
        name: 'onresize',
        attributeName: 'onresize',
        label: 'onresize',
        type: 'text',
        outputKind: 'event',
        jsRole: 'handler',
        description: 'Handler for column resize. Emitted only when a JavaScript identifier is set.',
        placeholder: 'handleResize',
      },
      {
        name: 'onloadmore',
        attributeName: 'onloadmore',
        label: 'onloadmore',
        type: 'text',
        outputKind: 'event',
        jsRole: 'handler',
        description: 'Handler for infinite loading. Emitted only when a JavaScript identifier is set.',
        placeholder: 'handleLoadMore',
      },
      {
        name: 'onsave',
        attributeName: 'onsave',
        label: 'onsave',
        type: 'text',
        outputKind: 'event',
        jsRole: 'handler',
        description: 'Handler for inline-edit save. Emitted only when a JavaScript identifier is set.',
        placeholder: 'handleSave',
      },
      {
        name: 'oncancel',
        attributeName: 'oncancel',
        label: 'oncancel',
        type: 'text',
        outputKind: 'event',
        jsRole: 'handler',
        description: 'Handler for inline-edit cancel. Emitted only when a JavaScript identifier is set.',
        placeholder: 'handleCancel',
      },
      {
        name: 'oncellchange',
        attributeName: 'oncellchange',
        label: 'oncellchange',
        type: 'text',
        outputKind: 'event',
        jsRole: 'handler',
        description: 'Handler for inline-edit cell changes. Emitted only when a JavaScript identifier is set.',
        placeholder: 'handleCellChange',
      },
    ],
    canvas: { kind: 'leaf', previewKind: 'datatable' },
    output: lwcOutput('lightning-datatable'),
  },
];
