import { Minus, AlignLeft, ChevronsUpDown, List, Circle } from 'lucide-react';
import type { ComponentDefinition } from '@/types/component';
import {
  COMBOBOX_VARIANT_OPTIONS,
  DATE_STYLE_OPTIONS,
  INPUT_TYPE_OPTIONS,
  LABEL_VARIANT_OPTIONS,
  NUMBER_FORMATTER_OPTIONS,
  RADIO_TYPE_OPTIONS,
  TIME_STYLE_OPTIONS,
} from '../shared/options';
import { LEAF_COMPOSITION, LEAF_SPACING, lwcOutput } from '../shared/composition';
import {
  INPUT_AUTOCOMPLETE_TYPES,
  INPUT_CHECKED_TYPES,
  INPUT_CHECKBOX_ONLY_TYPES,
  INPUT_DATE_STYLE_TYPES,
  INPUT_DATETIME_TYPES,
  INPUT_FILE_TYPES,
  INPUT_MIN_MAX_TYPES,
  INPUT_MULTIPLE_TYPES,
  INPUT_NO_HELP_TYPES,
  INPUT_NO_READONLY_TYPES,
  INPUT_NO_VALUE_TYPES,
  INPUT_NUMBER_ONLY_TYPES,
  INPUT_NUMBER_TYPES,
  INPUT_PLACEHOLDER_TYPES,
  INPUT_SEARCH_TYPES,
  INPUT_TEXT_TYPES,
  INPUT_TIME_STYLE_TYPES,
  INPUT_TOGGLE_TYPES,
  INPUT_TYPE_MISMATCH_TYPES,
  whenIn,
  whenNotIn,
} from '../shared/conditions';

export const FORM_COMPONENTS: ComponentDefinition[] = [
  {
    type: 'lightning-input',
    salesforceName: 'lightning-input',
    displayName: 'Input',
    category: 'Forms',
    description: 'An HTML input element that supports Salesforce input types including text, date, number, toggle, and file.',
    icon: Minus,
    composition: LEAF_COMPOSITION,
    styleCapabilities: LEAF_SPACING,
    defaultAttributes: {
      label: 'Input',
      type: 'text',
      placeholder: 'Enter value',
    },
    properties: [
      {
        name: 'label',
        attributeName: 'label',
        label: 'Label',
        type: 'text',
        defaultValue: 'Input',
        required: true,
        description: 'Text label for the input.',
        placeholder: 'Field label',
      },
      {
        name: 'type',
        attributeName: 'type',
        label: 'Type',
        type: 'select',
        defaultValue: 'text',
        description:
          'Valid values include checkbox, checkbox-button, color, date, datetime, time, email, file, password, range, search, tel, url, number, and toggle. Defaults to text.',
        options: INPUT_TYPE_OPTIONS,
      },
      {
        name: 'name',
        attributeName: 'name',
        label: 'Name',
        type: 'text',
        description: 'Specifies the name of an input element.',
        placeholder: 'Field name',
      },
      {
        name: 'value',
        attributeName: 'value',
        label: 'Value',
        type: 'text',
        description: 'Specifies the value of an input element.',
        placeholder: 'Initial value',
        visibleWhen: whenNotIn('type', INPUT_NO_VALUE_TYPES),
      },
      {
        name: 'placeholder',
        attributeName: 'placeholder',
        label: 'Placeholder',
        type: 'text',
        defaultValue: 'Enter value',
        description:
          'Displayed when the field is empty. Supported for date, email, number, password, search, tel, text, time, and url types.',
        placeholder: 'Hint text',
        visibleWhen: whenIn('type', INPUT_PLACEHOLDER_TYPES),
      },
      {
        name: 'required',
        attributeName: 'required',
        label: 'Required',
        type: 'boolean',
        defaultValue: false,
        description: 'If present, the field must be filled out before the form is submitted.',
      },
      {
        name: 'disabled',
        attributeName: 'disabled',
        label: 'Disabled',
        type: 'boolean',
        defaultValue: false,
        description: 'If present, users cannot interact with the field.',
      },
      {
        name: 'read-only',
        attributeName: 'read-only',
        label: 'Read Only',
        type: 'boolean',
        defaultValue: false,
        description: 'If present, the field cannot be edited.',
        visibleWhen: whenNotIn('type', INPUT_NO_READONLY_TYPES),
      },
      {
        name: 'checked',
        attributeName: 'checked',
        label: 'Checked',
        type: 'boolean',
        defaultValue: false,
        description: 'If present, the checkbox is selected. Used with checkbox and toggle types.',
        visibleWhen: whenIn('type', INPUT_CHECKED_TYPES),
      },
      {
        name: 'field-level-help',
        attributeName: 'field-level-help',
        label: 'Field Level Help',
        type: 'text',
        description:
          'Help text detailing the purpose of the input. Not supported for file, toggle, and checkbox-button types.',
        placeholder: 'Help text',
        visibleWhen: whenNotIn('type', INPUT_NO_HELP_TYPES),
      },
      {
        name: 'variant',
        attributeName: 'variant',
        label: 'Variant',
        type: 'select',
        defaultValue: 'standard',
        description:
          'Accepted variants: standard, label-inline, label-hidden, and label-stacked. Defaults to standard.',
        options: LABEL_VARIANT_OPTIONS,
      },
      {
        name: 'max-length',
        attributeName: 'max-length',
        label: 'Max Length',
        type: 'number',
        description:
          'Maximum characters allowed. Supported for email, password, search, tel, text, and url types.',
        placeholder: 'e.g. 255',
        visibleWhen: whenIn('type', INPUT_TEXT_TYPES),
      },
      {
        name: 'min-length',
        attributeName: 'min-length',
        label: 'Min Length',
        type: 'number',
        description:
          'Minimum characters allowed. Supported for email, password, search, tel, text, and url types.',
        placeholder: 'e.g. 0',
        visibleWhen: whenIn('type', INPUT_TEXT_TYPES),
      },
      {
        name: 'min',
        attributeName: 'min',
        label: 'Min',
        type: 'text',
        description:
          'Minimum acceptable value for number, range, date, time, and datetime types.',
        placeholder: 'Minimum value',
        visibleWhen: whenIn('type', INPUT_MIN_MAX_TYPES),
      },
      {
        name: 'max',
        attributeName: 'max',
        label: 'Max',
        type: 'text',
        description:
          'Maximum acceptable value for number, range, date, time, and datetime types.',
        placeholder: 'Maximum value',
        visibleWhen: whenIn('type', INPUT_MIN_MAX_TYPES),
      },
      {
        name: 'step',
        attributeName: 'step',
        label: 'Step',
        type: 'text',
        defaultValue: '1',
        description:
          "Granularity for number and range types. Use 'any' when granularity is not a concern. Defaults to 1.",
        placeholder: 'e.g. 1',
        visibleWhen: whenIn('type', INPUT_NUMBER_TYPES),
      },
      {
        name: 'pattern',
        attributeName: 'pattern',
        label: 'Pattern',
        type: 'text',
        description:
          'Regular expression used for email, password, search, tel, text, and url types.',
        placeholder: 'Regex pattern',
        visibleWhen: whenIn('type', INPUT_TEXT_TYPES),
      },
      {
        name: 'formatter',
        attributeName: 'formatter',
        label: 'Formatter',
        type: 'select',
        description: 'Formatter for number input: decimal, percent, percent-fixed, or currency.',
        options: [{ label: 'None', value: '' }, ...NUMBER_FORMATTER_OPTIONS],
        visibleWhen: whenIn('type', INPUT_NUMBER_ONLY_TYPES),
      },
      {
        name: 'autocomplete',
        attributeName: 'autocomplete',
        label: 'Autocomplete',
        type: 'text',
        description:
          'Controls auto-filling. Use with email, search, tel, text, and url types.',
        placeholder: 'e.g. email',
        visibleWhen: whenIn('type', INPUT_AUTOCOMPLETE_TYPES),
      },
      {
        name: 'multiple',
        attributeName: 'multiple',
        label: 'Multiple',
        type: 'boolean',
        defaultValue: false,
        description: 'If present, more than one value can be entered. Use with file and email types.',
        visibleWhen: whenIn('type', INPUT_MULTIPLE_TYPES),
      },
      {
        name: 'accept',
        attributeName: 'accept',
        label: 'Accept',
        type: 'text',
        description: 'File types the server accepts. Use with file input type only.',
        placeholder: 'e.g. .csv,image/*',
        visibleWhen: whenIn('type', INPUT_FILE_TYPES),
      },
      {
        name: 'is-loading',
        attributeName: 'is-loading',
        label: 'Is Loading',
        type: 'boolean',
        defaultValue: false,
        description: 'For search type only. If present, a spinner indicates that data is loading.',
        visibleWhen: whenIn('type', INPUT_SEARCH_TYPES),
      },
      {
        name: 'indeterminate',
        attributeName: 'indeterminate',
        label: 'Indeterminate',
        type: 'boolean',
        defaultValue: false,
        description: 'Checkbox-only. Displays a dash instead of checked or unchecked.',
        visibleWhen: whenIn('type', INPUT_CHECKBOX_ONLY_TYPES),
      },
      {
        name: 'date-style',
        attributeName: 'date-style',
        label: 'Date Style',
        type: 'select',
        defaultValue: 'medium',
        description: "Display style when type is date or datetime. Valid values: short, medium, long. Defaults to medium.",
        options: DATE_STYLE_OPTIONS,
        visibleWhen: whenIn('type', INPUT_DATE_STYLE_TYPES),
      },
      {
        name: 'time-style',
        attributeName: 'time-style',
        label: 'Time Style',
        type: 'select',
        defaultValue: 'short',
        description: "Display style when type is time or datetime. Valid values: short, medium, long. Defaults to short.",
        options: TIME_STYLE_OPTIONS,
        visibleWhen: whenIn('type', INPUT_TIME_STYLE_TYPES),
      },
      {
        name: 'timezone',
        attributeName: 'timezone',
        label: 'Timezone',
        type: 'text',
        description: "Time zone used when type is datetime. Defaults to the user's Salesforce time zone.",
        placeholder: 'e.g. America/Los_Angeles',
        visibleWhen: whenIn('type', INPUT_DATETIME_TYPES),
      },
      {
        name: 'time-step-minutes',
        attributeName: 'time-step-minutes',
        label: 'Time Step Minutes',
        type: 'number',
        defaultValue: 15,
        description: 'Time interval in minutes for dropdown options. Integer of 5 or more. Defaults to 15.',
        visibleWhen: whenIn('type', INPUT_TIME_STYLE_TYPES),
      },
      {
        name: 'message-toggle-active',
        attributeName: 'message-toggle-active',
        label: 'Toggle Active Message',
        type: 'text',
        description: 'Text shown for the active state of a toggle. Defaults to Active.',
        placeholder: 'Active',
        visibleWhen: whenIn('type', INPUT_TOGGLE_TYPES),
      },
      {
        name: 'message-toggle-inactive',
        attributeName: 'message-toggle-inactive',
        label: 'Toggle Inactive Message',
        type: 'text',
        description: 'Text shown for the inactive state of a toggle. Defaults to Inactive.',
        placeholder: 'Inactive',
        visibleWhen: whenIn('type', INPUT_TOGGLE_TYPES),
      },
      {
        name: 'message-when-value-missing',
        attributeName: 'message-when-value-missing',
        label: 'Message When Value Missing',
        type: 'text',
        description: 'Error message when the required attribute is set and the value is missing.',
      },
      {
        name: 'message-when-bad-input',
        attributeName: 'message-when-bad-input',
        label: 'Message When Bad Input',
        type: 'text',
        description: 'Error message when a bad input is detected.',
      },
      {
        name: 'message-when-pattern-mismatch',
        attributeName: 'message-when-pattern-mismatch',
        label: 'Message When Pattern Mismatch',
        type: 'text',
        description: 'Error message when a pattern mismatch is detected.',
        visibleWhen: whenIn('type', INPUT_TEXT_TYPES),
      },
      {
        name: 'message-when-too-long',
        attributeName: 'message-when-too-long',
        label: 'Message When Too Long',
        type: 'text',
        description: 'Error message when the value exceeds max-length.',
        visibleWhen: whenIn('type', INPUT_TEXT_TYPES),
      },
      {
        name: 'message-when-too-short',
        attributeName: 'message-when-too-short',
        label: 'Message When Too Short',
        type: 'text',
        description: 'Error message when the value is below min-length.',
        visibleWhen: whenIn('type', INPUT_TEXT_TYPES),
      },
      {
        name: 'message-when-type-mismatch',
        attributeName: 'message-when-type-mismatch',
        label: 'Message When Type Mismatch',
        type: 'text',
        description: 'Error message for email and url type mismatches.',
        visibleWhen: whenIn('type', INPUT_TYPE_MISMATCH_TYPES),
      },
      {
        name: 'message-when-range-overflow',
        attributeName: 'message-when-range-overflow',
        label: 'Message When Range Overflow',
        type: 'text',
        description: 'Error message when a max value is exceeded.',
        visibleWhen: whenIn('type', INPUT_MIN_MAX_TYPES),
      },
      {
        name: 'message-when-range-underflow',
        attributeName: 'message-when-range-underflow',
        label: 'Message When Range Underflow',
        type: 'text',
        description: 'Error message when a min value is not met.',
        visibleWhen: whenIn('type', INPUT_MIN_MAX_TYPES),
      },
      {
        name: 'message-when-step-mismatch',
        attributeName: 'message-when-step-mismatch',
        label: 'Message When Step Mismatch',
        type: 'text',
        description: 'Error message when a step mismatch is detected.',
        visibleWhen: whenIn('type', INPUT_NUMBER_TYPES),
      },
    ],
    canvas: { kind: 'leaf', previewKind: 'input', previewLabelProperty: 'label' },
    output: lwcOutput('lightning-input'),
  },

  {
    type: 'lightning-textarea',
    salesforceName: 'lightning-textarea',
    displayName: 'Textarea',
    category: 'Forms',
    description: 'A multi-line text input field.',
    icon: AlignLeft,
    composition: LEAF_COMPOSITION,
    styleCapabilities: LEAF_SPACING,
    defaultAttributes: {
      label: 'Textarea',
      placeholder: 'Enter text',
    },
    properties: [
      {
        name: 'label',
        attributeName: 'label',
        label: 'Label',
        type: 'text',
        defaultValue: 'Textarea',
        required: true,
        description: 'Text that describes the textarea input field.',
        placeholder: 'Field label',
      },
      {
        name: 'name',
        attributeName: 'name',
        label: 'Name',
        type: 'text',
        description: 'Specifies the name of an input element.',
        placeholder: 'Field name',
      },
      {
        name: 'value',
        attributeName: 'value',
        label: 'Value',
        type: 'text',
        description: 'The value of the textarea, also used as the default value during init.',
        placeholder: 'Initial value',
      },
      {
        name: 'placeholder',
        attributeName: 'placeholder',
        label: 'Placeholder',
        type: 'text',
        defaultValue: 'Enter text',
        description: 'Text displayed when the field is empty.',
        placeholder: 'Hint text',
      },
      {
        name: 'required',
        attributeName: 'required',
        label: 'Required',
        type: 'boolean',
        defaultValue: false,
        description: 'If present, the field must be filled out before the form can be submitted.',
      },
      {
        name: 'disabled',
        attributeName: 'disabled',
        label: 'Disabled',
        type: 'boolean',
        defaultValue: false,
        description: 'If present, users cannot interact with the field.',
      },
      {
        name: 'read-only',
        attributeName: 'read-only',
        label: 'Read Only',
        type: 'boolean',
        defaultValue: false,
        description: 'If present, the field cannot be edited.',
      },
      {
        name: 'max-length',
        attributeName: 'max-length',
        label: 'Max Length',
        type: 'number',
        description: 'The maximum number of characters allowed in the textarea.',
        placeholder: 'e.g. 255',
      },
      {
        name: 'min-length',
        attributeName: 'min-length',
        label: 'Min Length',
        type: 'number',
        description: 'The minimum number of characters allowed in the textarea.',
        placeholder: 'e.g. 0',
      },
      {
        name: 'autocomplete',
        attributeName: 'autocomplete',
        label: 'Autocomplete',
        type: 'text',
        description: 'Controls auto-filling of the field.',
      },
      {
        name: 'variant',
        attributeName: 'variant',
        label: 'Variant',
        type: 'select',
        defaultValue: 'standard',
        description:
          'Accepted variants: standard, label-hidden, label-inline, and label-stacked. Defaults to standard.',
        options: LABEL_VARIANT_OPTIONS,
      },
      {
        name: 'message-when-value-missing',
        attributeName: 'message-when-value-missing',
        label: 'Message When Value Missing',
        type: 'text',
        description: 'Error message when the value is missing.',
      },
      {
        name: 'message-when-too-long',
        attributeName: 'message-when-too-long',
        label: 'Message When Too Long',
        type: 'text',
        description: 'Error message when the value is too long.',
      },
      {
        name: 'message-when-too-short',
        attributeName: 'message-when-too-short',
        label: 'Message When Too Short',
        type: 'text',
        description: 'Error message when the value is too short.',
      },
      {
        name: 'message-when-bad-input',
        attributeName: 'message-when-bad-input',
        label: 'Message When Bad Input',
        type: 'text',
        description: 'Error message when a bad input is detected.',
      },
    ],
    canvas: { kind: 'leaf', previewKind: 'textarea', previewLabelProperty: 'label' },
    output: lwcOutput('lightning-textarea'),
  },

  {
    type: 'lightning-combobox',
    salesforceName: 'lightning-combobox',
    displayName: 'Combobox',
    category: 'Forms',
    description:
      'A read-only input with a dropdown list of selectable options. Multiple selection is not supported. Options are passed from JavaScript, not HTML.',
    icon: ChevronsUpDown,
    composition: LEAF_COMPOSITION,
    styleCapabilities: LEAF_SPACING,
    defaultAttributes: {
      label: 'Combobox',
      placeholder: 'Select an option',
    },
    properties: [
      {
        name: 'label',
        attributeName: 'label',
        label: 'Label',
        type: 'text',
        defaultValue: 'Combobox',
        required: true,
        description: 'Text label for the combobox.',
        placeholder: 'Field label',
      },
      {
        name: 'name',
        attributeName: 'name',
        label: 'Name',
        type: 'text',
        description: 'Specifies the name of the input element.',
        placeholder: 'Field name',
      },
      {
        name: 'value',
        attributeName: 'value',
        label: 'Value',
        type: 'text',
        description: 'The value of the selected option.',
        placeholder: 'Selected value',
      },
      {
        name: 'placeholder',
        attributeName: 'placeholder',
        label: 'Placeholder',
        type: 'text',
        defaultValue: 'Select an option',
        description: 'Text displayed when no option is selected.',
        placeholder: 'Hint text',
      },
      {
        name: 'options',
        attributeName: 'options',
        label: 'Options',
        type: 'text',
        htmlAttribute: false,
        description:
          'JavaScript array of {label, value} objects, with optional description and iconName. Not an HTML attribute.',
        placeholder: 'Defined in JS',
      },
      {
        name: 'required',
        attributeName: 'required',
        label: 'Required',
        type: 'boolean',
        defaultValue: false,
        description: 'If present, an option must be selected.',
      },
      {
        name: 'disabled',
        attributeName: 'disabled',
        label: 'Disabled',
        type: 'boolean',
        defaultValue: false,
        description: 'If present, users cannot interact with the combobox.',
      },
      {
        name: 'read-only',
        attributeName: 'read-only',
        label: 'Read Only',
        type: 'boolean',
        defaultValue: false,
        description: 'If present, the combobox cannot be edited.',
      },
      {
        name: 'variant',
        attributeName: 'variant',
        label: 'Variant',
        type: 'select',
        defaultValue: 'standard',
        description:
          'Accepted variants: standard, label-hidden, label-inline, label-stacked, and button. The button variant supports option icons.',
        options: COMBOBOX_VARIANT_OPTIONS,
      },
      {
        name: 'field-level-help',
        attributeName: 'field-level-help',
        label: 'Field Level Help',
        type: 'text',
        description: 'Help text detailing the purpose of the combobox.',
        placeholder: 'Help text',
      },
      {
        name: 'message-when-value-missing',
        attributeName: 'message-when-value-missing',
        label: 'Message When Value Missing',
        type: 'text',
        description: 'Error message when a required combobox has no selection.',
      },
    ],
    canvas: { kind: 'leaf', previewKind: 'combobox', previewLabelProperty: 'label' },
    output: lwcOutput('lightning-combobox'),
  },

  {
    type: 'lightning-checkbox-group',
    salesforceName: 'lightning-checkbox-group',
    displayName: 'Checkbox Group',
    category: 'Forms',
    description:
      'A group of checkboxes that enables selection of one or more options. Options are passed from JavaScript.',
    icon: List,
    composition: LEAF_COMPOSITION,
    styleCapabilities: LEAF_SPACING,
    defaultAttributes: {
      label: 'Checkbox Group',
    },
    properties: [
      {
        name: 'label',
        attributeName: 'label',
        label: 'Label',
        type: 'text',
        defaultValue: 'Checkbox Group',
        required: true,
        description: 'Text label for the checkbox group.',
        placeholder: 'Group label',
      },
      {
        name: 'name',
        attributeName: 'name',
        label: 'Name',
        type: 'text',
        description: 'Specifies the name of the checkbox group.',
        placeholder: 'Field name',
      },
      {
        name: 'options',
        attributeName: 'options',
        label: 'Options',
        type: 'text',
        htmlAttribute: false,
        description:
          'JavaScript array of {label, value} objects. Not an HTML attribute.',
        placeholder: 'Defined in JS',
      },
      {
        name: 'value',
        attributeName: 'value',
        label: 'Value',
        type: 'text',
        htmlAttribute: false,
        description: 'JavaScript array of selected option values. Not an HTML attribute.',
        placeholder: 'Selected values',
      },
      {
        name: 'required',
        attributeName: 'required',
        label: 'Required',
        type: 'boolean',
        defaultValue: false,
        description: 'If present, at least one checkbox must be selected.',
      },
      {
        name: 'disabled',
        attributeName: 'disabled',
        label: 'Disabled',
        type: 'boolean',
        defaultValue: false,
        description: 'If present, checkbox selections cannot be changed.',
      },
      {
        name: 'variant',
        attributeName: 'variant',
        label: 'Variant',
        type: 'select',
        defaultValue: 'standard',
        description:
          'Accepted variants: standard, label-hidden, label-inline, and label-stacked. Defaults to standard.',
        options: LABEL_VARIANT_OPTIONS,
      },
      {
        name: 'message-when-value-missing',
        attributeName: 'message-when-value-missing',
        label: 'Message When Value Missing',
        type: 'text',
        description:
          'Error message when the group is required and no option is selected. Overrides the default Complete this field message.',
      },
    ],
    canvas: { kind: 'leaf', previewKind: 'checkbox-group', previewLabelProperty: 'label' },
    output: lwcOutput('lightning-checkbox-group'),
  },

  {
    type: 'lightning-radio-group',
    salesforceName: 'lightning-radio-group',
    displayName: 'Radio Group',
    category: 'Forms',
    description:
      'A radio button group that permits only one option to be selected. Options are passed from JavaScript.',
    icon: Circle,
    composition: LEAF_COMPOSITION,
    styleCapabilities: LEAF_SPACING,
    defaultAttributes: {
      label: 'Radio Group',
      type: 'radio',
    },
    properties: [
      {
        name: 'label',
        attributeName: 'label',
        label: 'Label',
        type: 'text',
        defaultValue: 'Radio Group',
        required: true,
        description: 'Text label for the radio group. Rendered as a fieldset legend.',
        placeholder: 'Group label',
      },
      {
        name: 'name',
        attributeName: 'name',
        label: 'Name',
        type: 'text',
        description:
          'Name shared by the radio inputs. Omit to let the component generate a unique name.',
        placeholder: 'Field name',
      },
      {
        name: 'options',
        attributeName: 'options',
        label: 'Options',
        type: 'text',
        htmlAttribute: false,
        description:
          'JavaScript array of {label, value} objects. Not an HTML attribute.',
        placeholder: 'Defined in JS',
      },
      {
        name: 'value',
        attributeName: 'value',
        label: 'Value',
        type: 'text',
        description: 'The value of the selected radio button.',
        placeholder: 'Selected value',
      },
      {
        name: 'type',
        attributeName: 'type',
        label: 'Type',
        type: 'select',
        defaultValue: 'radio',
        description: 'The style of the radio group. Options are radio or button. Defaults to radio.',
        options: RADIO_TYPE_OPTIONS,
      },
      {
        name: 'required',
        attributeName: 'required',
        label: 'Required',
        type: 'boolean',
        defaultValue: false,
        description: 'If present, a radio button must be selected before the form can be submitted.',
      },
      {
        name: 'disabled',
        attributeName: 'disabled',
        label: 'Disabled',
        type: 'boolean',
        defaultValue: false,
        description: 'If present, users cannot interact with the radio buttons.',
      },
      {
        name: 'variant',
        attributeName: 'variant',
        label: 'Variant',
        type: 'select',
        defaultValue: 'standard',
        description:
          'Accepted variants: standard, label-hidden, label-inline, and label-stacked. Defaults to standard.',
        options: LABEL_VARIANT_OPTIONS,
      },
      {
        name: 'message-when-value-missing',
        attributeName: 'message-when-value-missing',
        label: 'Message When Value Missing',
        type: 'text',
        description:
          'Error message when no radio button is selected and required is true.',
      },
    ],
    canvas: { kind: 'leaf', previewKind: 'radio-group', previewLabelProperty: 'label' },
    output: lwcOutput('lightning-radio-group'),
  },
];
